"""Pipeline orchestration for Stock Scout."""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Iterable

import pandas as pd

from .alerts import notify
from .config import Filters, ScoringWeights, Settings
from .data_ingestion import (
    fetch_bulk_block_deals,
    fetch_corporate_events,
    fetch_market_data_with_indicators,
    fetch_recent_corporate_actions,
    fetch_recent_filings,
    fetch_recent_news_with_sentiment,
    fetch_universe,
)
from .scoring import rank_candidates


@dataclass
class PipelineArtifacts:
    """Artifacts generated by the weekly pipeline."""

    universe: pd.DataFrame
    prices: pd.DataFrame
    indicators: pd.DataFrame
    events: pd.DataFrame
    filings: pd.DataFrame
    actions: pd.DataFrame
    flows: pd.DataFrame
    news: pd.DataFrame
    features: pd.DataFrame
    scores: pd.DataFrame
    top_candidates: pd.DataFrame


def assemble_features(
    universe: pd.DataFrame,
    prices: pd.DataFrame,
    indicators: pd.DataFrame,
    events: pd.DataFrame,
    filings: pd.DataFrame,
    actions: pd.DataFrame,
    flows: pd.DataFrame,
    news: pd.DataFrame,
) -> pd.DataFrame:
    """Combine datasets into a single feature matrix."""

    latest_prices = prices.sort_values("date").groupby("symbol").tail(1)
    latest_prices = latest_prices.merge(universe, on="symbol", how="left")
    latest_indicators = indicators.sort_values("date").groupby("symbol").tail(1)

    df = latest_prices.merge(latest_indicators, on="symbol", how="left", suffixes=("", "_ind"))
    df["momentum"] = df["breakout_score"].fillna(0)
    df["volume_thrust"] = df["vol_percentile"].fillna(0)
    df["growth"] = 50  # placeholder until fundamental API wired

    def _group_count(frame: pd.DataFrame, column: str, name: str) -> pd.Series:
        if column not in frame.columns or frame.empty:
            return pd.Series(dtype="float64", name=name)
        return frame.groupby(column).size().rename(name)

    def _group_mean(frame: pd.DataFrame, group_col: str, value_col: str, name: str) -> pd.Series:
        if frame.empty or group_col not in frame.columns or value_col not in frame.columns:
            return pd.Series(dtype="float64", name=name)
        return frame.groupby(group_col)[value_col].mean().rename(name)

    upcoming_events = _group_count(events, "symbol", "event_count")
    recent_filings = _group_count(filings, "symbol", "filing_count")
    corp_actions = _group_count(actions, "symbol", "corp_action_count")
    flow_hits = _group_count(flows, "symbol", "flow_count")
    news_sent = _group_mean(news, "symbol", "sentiment", "sentiment")

    df = df.set_index("symbol")
    df["catalyst"] = (
        upcoming_events.add(recent_filings, fill_value=0)
        .add(corp_actions, fill_value=0)
        .fillna(0)
    )
    df["flow"] = flow_hits.reindex(df.index).fillna(0)
    df["sentiment"] = news_sent.reindex(df.index).fillna(0)
    df["avg_turnover_inr"] = (df["close"] * df["volume"]).fillna(0)
    df["atr_pct"] = (df["atr"] / df["close"]).fillna(0)
    df["breakout_level"] = df["high"]
    sector_series = df.get("sector")
    if sector_series is None:
        sector_series = pd.Series("Unknown", index=df.index)
    df["sector"] = sector_series.fillna("Unknown")
    return df


def run_weekly_pipeline(settings: Settings) -> PipelineArtifacts:
    """Execute the full Saturday morning cadence."""

    universe = fetch_universe(settings.api_keys.twelve_data)
    market = fetch_market_data_with_indicators(universe["symbol"], settings.api_keys.twelve_data)
    events = fetch_corporate_events()
    filings = fetch_recent_filings()
    actions = fetch_recent_corporate_actions()
    flows = fetch_bulk_block_deals()
    news = fetch_recent_news_with_sentiment(universe["symbol"], settings.api_keys.finnhub)

    features = assemble_features(
        universe=universe,
        prices=market.prices,
        indicators=market.indicators,
        events=events,
        filings=filings,
        actions=actions,
        flows=flows,
        news=news,
    )

    scoring_result = rank_candidates(features, settings.scoring, settings.filters)
    notify(settings.outputs, scoring_result.top_candidates)

    return PipelineArtifacts(
        universe=universe,
        prices=market.prices,
        indicators=market.indicators,
        events=events,
        filings=filings,
        actions=actions,
        flows=flows,
        news=news,
        features=features,
        scores=scoring_result.scores,
        top_candidates=scoring_result.top_candidates,
    )


def run_intraday_monitor(symbols: Iterable[str], settings: Settings) -> pd.DataFrame:
    """Lightweight intraday monitor that checks for breakout continuation."""

    market = fetch_market_data_with_indicators(symbols, settings.api_keys.twelve_data)
    latest = market.prices.sort_values("date").groupby("symbol").tail(1).set_index("symbol")
    indicators = market.indicators.sort_values("date").groupby("symbol").tail(1).set_index("symbol")
    merged = latest.join(indicators, how="left", lsuffix="_price", rsuffix="_ind")

    volume_ref = (
        market.prices.sort_values("date")
        .groupby("symbol")["volume"]
        .apply(lambda s: s.tail(20).mean())
    )
    merged["breakout_confirmed"] = merged["close"] >= merged["donchian20_high"]
    merged["volume_spike"] = merged["volume"] >= 1.5 * volume_ref.reindex(merged.index).fillna(0)
    return merged[["close", "breakout_confirmed", "volume_spike"]]


__all__ = ["PipelineArtifacts", "run_intraday_monitor", "run_weekly_pipeline"]
